--- #YAML:1.0
name:                Hash-Path
version:             0.01
abstract:            A simple way to return a path of HoH
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Igor Sutton Lopes <igor.sutton@gmail.com>
